# -*- coding: utf-8 -*-
# Copyright 2023 OpenSPG Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

import json
from string import Template
from typing import List

from kag.builder.prompt.default.util import load_NER_data
from kag.common.conf import KAG_PROJECT_CONF
from kag.interface import PromptABC
from knext.schema.client import SchemaClient


@PromptABC.register("knowledge_unit_ner")
class OpenIENERKnowledgeUnitPrompt(PromptABC):
    template_en = """
You are a highly efficient entity extraction system. Based on a given schema that constrains entity categories, your task is to thoroughly analyze source texts and extract all mentioned entities with their names, types, domain ontologies, explanations, standard names, and synonyms. 
Entities must strictly adhere to the schema's predefined types.

If the entity type does not exist, return an empty list. Please respond in JSON list format, where each entity is represented as a list. If there are no entities of a given type, return an empty list. The format is as follows:
[
    {
        "Name": An entity noun/proper noun/gerund from the text with real-world significance (avoid generic terms like 'air conditioner' or pronouns),
        "Category": Entity category strictly following schema classifications (use 'Other' if unclassifiable),
        "Domain Ontology": A taxonomic hierarchy of hypernyms and hyponyms within the entity's disciplinary or professional domain, structured as a hierarchical chain from broad to specific domain-specific concepts. Avoid directly placing the entity itself into the ontology,
        "Description": A descriptive text for each entity generated by integrating contextual information and domain-specific knowledge, avoiding the use of pronouns,
        "Standard Name": The standard name of the entity, in case it is colloquial, abbreviated, or informal in the text,
        "Synonyms": All synonyms of the entity based on knowledge.
    },
    {},
    ……
]

### schema
[ 
$schema
]

### Example:
input:Dr. Zhang Wei (born July 15, 1980), a Chinese geneticist from Beijing, attended the 2023 International Biodiversity Summit in the Alps. He presented findings on Panthera tigris altaica, a critically endangered subspecies. The conference coincided with the enforcement of EU Regulation No. 1143/2023, which restricts trade in endangered species.
output:
[
    {
        "Name": "Zhang Wei",
        "Category": "Person",
        "Domain Ontology": "Human -> Scientist -> Geneticist",
        "Description": "A Chinese geneticist known for attending the 2023 International Biodiversity Summit",
        "Standard Name": "Zhang Wei",
        "Synonyms": []
    },
    {
        "Name": "Alps",
        "Category": "Geographic Location",
        "Domain Ontology": "Physical Geography -> Mountain Range",
        "Description": "A major European mountain range hosting the biodiversity summit",
        "Standard Name": "Alps",
        "Synonyms": ["The Alpine Region"]
    },
    {
        "Name": "2023 International Biodiversity Summit",
        "Category": "Event",
        "Domain Ontology": "Conference -> Scientific Conference -> Environmental Conference",
        "Description": "An international conference focused on biodiversity conservation held in 2023",
        "Standard Name": "2023 International Biodiversity Summit",
        "Synonyms": []
    },
    {
        "Name": "EU Regulation No. 1143/2023",
        "Category": "Policy and Regulation",
        "Domain Ontology": "Legal Framework -> Environmental Law -> Trade Regulation",
        "Description": "Legislation restricting trade of endangered species",
        "Standard Name": "Regulation (EU) No 1143/2023",
        "Synonyms": []
    },
    {
        "Name": "Panthera tigris altaica",
        "Category": "Creature",
        "Domain Ontology": "Animalia -> Chordata -> Mammalia -> Carnivora -> Felidae -> Panthera",
        "Description": "A critically endangered tiger subspecies discussed at the summit",
        "Standard Name": "Panthera tigris altaica",
        "Synonyms": ["Amur Tiger"]
    }
]
### Input:
input:$input
        """

    template_zh = """您是一个专业的军事部署领域实体抽取系统。根据给定的军事部署实体类别的模式（schema），您的任务是全面分析源文本，并提取所有提及到的军事部署相关实体及其对应的名称、类型、领域本体、解释说明、标准名称和同义词。
实体必须严格符合schema中的预定义军事部署类型（如：军事单位、战术形式、相对位置、防御阵地、指挥所、障碍物、武器等）。

如果实体类型不存在于schema中，则返回空列表。结果请以JSON列表格式响应，其中每个实体以一个字典表示。如果在给定类型中没有实体，则返回空列表。格式如下：
[
    {
        "名称":一个出现在原文中的军事部署相关实体名词、专有名词或者动名词，具有明确的军事意义，避免模糊词和代词，
        "类型":指实体的分类，严格根据类别划分到给定Schema中具有的军事部署类型（如MilitaryUnit、CombatForm、RelativePosition、DefensePosition、CommandPost、Obstacle、Weapon等），无法划分则返回空列表,
        "领域本体":当前实体所属军事领域的上下位词构成的分类体系，整体是一个由粗到细的军事概念上下位逻辑链（如：军事 -> 兵种 -> 地面部队），避免将实体直接放入领域本体。
        "解释":结合上下文及你的军事知识，对每个实体生产一段描述性的文本，说明其在军事部署中的作用和特点，避免使用代词,
        "标准名":文中的实体名可能是俗称、缩写或非标准表述，结合你的军事知识，给实体一个标准军事术语名称,该名称应当尽可能和其他同名实体消除歧义,
        "同义词":根据你的军事知识列出实体的所有同义词或常用表述
    },
    {},
    ……
]

### schema
[ 
$schema
]

### Example:
input: 标题: 现代战场兵种部署
内容: 在现代战场上，兵种在不同战术形式下的相对位置具有明确的规定，以确保各兵种的最大战术效能。在进攻形式下，兵种部署的目的是突破敌人防线并迅速推进。步兵通常位于最前方，处于整个队形的最前端，直接向敌人阵地推进，承担冲锋和占领敌方阵地的任务。紧随步兵之后的是坦克，通常部署在步兵的后方或稍偏两侧，负责为步兵提供火力支援并突破敌方的防线。炮兵通常部署在后方，位于队形的中央或偏后的位置，提供远程火力支援，用于打击敌方的阵地和重武器。航空兵则位于空中，通常处于整个战场的上空，提供空中打击和侦察，压制敌方空防并摧毁敌方后方的补给线和指挥设施。通信兵则部署在指挥中心，通常位于队伍的后方或侧翼，确保前线部队与指挥中心之间的信息传递流畅，保证指挥系统的有效运作。
output:[
    {
        "名称": "进攻形式",
        "类型": "CombatForm",
        "领域本体": "军事 -> 战术 -> 进攻战术",
        "解释": "进攻形式是一种战术形式，旨在突破敌人防线并迅速推进，以实现战场上的主动权和目标占领。",
        "标准名": "进攻战术",
        "同义词": ["进攻", "攻击形式", "进攻行动"]
    },
    {
        "名称": "步兵",
        "类型": "MilitaryUnit",
        "领域本体": "军事 -> 兵种 -> 地面部队",
        "解释": "步兵是地面作战的基本军事单位，通常位于队形最前端，负责冲锋和占领敌方阵地。",
        "标准名": "步兵部队",
        "同义词": ["步兵兵种", "步兵单位"]
    },
    {
        "名称": "坦克",
        "类型": "MilitaryUnit",
        "领域本体": "军事 -> 兵种 -> 装甲部队",
        "解释": "坦克是装甲军事单位，通常部署在步兵后方或两侧，提供火力支援并突破敌方防线。",
        "标准名": "坦克部队",
        "同义词": ["装甲部队", "坦克兵种"]
    },
    {
        "名称": "炮兵",
        "类型": "MilitaryUnit",
        "领域本体": "军事 -> 兵种 -> 火力支援部队",
        "解释": "炮兵是远程火力支援军事单位，通常部署在后方，用于打击敌方阵地和重武器。",
        "标准名": "炮兵部队",
        "同义词": ["火炮部队", "炮兵兵种"]
    },
    {
        "名称": "航空兵",
        "类型": "MilitaryUnit",
        "领域本体": "军事 -> 兵种 -> 空中部队",
        "解释": "航空兵是空中作战军事单位，通常位于战场上空，提供空中打击、侦察和压制敌方空防。",
        "标准名": "航空兵部队",
        "同义词": ["空军部队", "空中兵种"]
    },
    {
        "名称": "通信兵",
        "类型": "MilitaryUnit",
        "领域本体": "军事 -> 兵种 -> 通信支援部队",
        "解释": "通信兵是负责信息传递的军事单位，通常部署在指挥中心附近，确保前线与指挥系统之间的通信流畅。",
        "标准名": "通信兵部队",
        "同义词": ["通信部队", "通信兵种"]
    },
    {
        "名称": "队形",
        "类型": "Formation",
        "领域本体": "军事 -> 战术 -> 部署结构",
        "解释": "队形是部队在战场上的排列和部署结构，用于优化战术效能和协调各兵种行动。",
        "标准名": "战术队形",
        "同义词": ["阵型", "部署队形"]
    },
    {
        "名称": "最前方",
        "类型": "RelativePosition",
        "领域本体": "军事 -> 战术 -> 空间关系",
        "解释": "最前方指兵种在战场上的空间位置，位于整个队形的最前端，通常由步兵占据。",
        "标准名": "最前方",
        "同义词": ["最前端", "前方"]
    },
    {
        "名称": "后方",
        "类型": "RelativePosition",
        "领域本体": "军事 -> 战术 -> 空间关系",
        "解释": "后方指兵种在战场上的空间位置，位于队形的后方，通常部署炮兵等支援单位。",
        "标准名": "后方",
        "同义词": ["后侧", "后部"]
    },
    {
        "名称": "侧翼",
        "类型": "RelativePosition",
        "领域本体": "军事 -> 战术 -> 空间关系",
        "解释": "侧翼指兵种在战场上的空间位置，位于队伍的侧翼，通常部署通信兵等辅助单位。",
        "标准名": "侧翼",
        "同义词": ["侧方", "侧面"]
    },
    {
        "名称": "指挥中心",
        "类型": "CommandPost",
        "领域本体": "军事 -> 设施 -> 指挥设施",
        "解释": "指挥中心是战场上的指挥设施，通常位于后方或侧翼，负责协调部队行动和决策。",
        "标准名": "指挥所",
        "同义词": ["指挥部", "指挥设施"]
    },
    {
        "名称": "敌方阵地",
        "类型": "DefensePosition",
        "领域本体": "军事 -> 设施 -> 防御设施",
        "解释": "敌方阵地是敌人部署的防御设施，通常包括工事和火力点，用于抵抗进攻。",
        "标准名": "敌方防御阵地",
        "同义词": ["敌人阵地", "防御工事"]
    }
]
### Input:
input: $input
"""

    def __init__(self, language: str = "", **kwargs):
        super().__init__(language, **kwargs)
        self.schema = SchemaClient(
            host_addr=KAG_PROJECT_CONF.host_addr, project_id=KAG_PROJECT_CONF.project_id
        ).extract_types(KAG_PROJECT_CONF.language)
        self.template = Template(self.template).safe_substitute(
            schema=json.dumps(self.schema, ensure_ascii=False)
        )

    @property
    def template_variables(self) -> List[str]:
        return ["input"]

    def process_data(self, response: str, **kwargs):
        rsp = response
        if isinstance(rsp, str):
            rsp = json.loads(rsp)
        if isinstance(rsp, dict) and "output" in rsp:
            rsp = rsp["output"]
        return rsp

    def process_en(self, response: dict, **kwargs):
        """ "Name": "2023 International Biodiversity Summit",
        "Category": "Event",
        "Domain Ontology": "Conference -> Scientific Conference -> Environmental Conference",
        "Description": "An international conference focused on biodiversity conservation held in 2023",
        "Standard Name": "2023 International Biodiversity Summit",
        "Synonyms": []"""
        ret = {}
        if "Name" in response.keys():
            ret["name"] = response["Name"]
        if "Category" in response.keys():
            ret["category"] = response["Category"]
        if "Domain Ontology" in response.keys():
            ret["ontology"] = response["Domain Ontology"]
            if isinstance(ret["ontology"], list):
                ret["ontology"] = " -> ".join(ret["ontology"])
        if "Standard Name" in response.keys():
            ret["officialName"] = response["Standard Name"]
        if "Synonyms" in response.keys():
            ret["synonyms"] = response["Synonyms"]
        if "Description" in response.keys():
            ret["description"] = response["Description"]
        return ret

    def process_zh(self, response: dict, **kwargs):
        """{
            "名称": "当阳县五七干校",
            "类型": "组织机构",
            "领域本体": "教育 -> 历史教育机构 -> 五七干校",
            "解释": "当阳县五七干校是1975年2月根据县委指示增设的一所干校，于1978年8月撤销。",
            "标准名": "当阳县五七干校",
            "同义词": []
        }"""
        ret = {}
        if "名称" in response.keys():
            ret["name"] = response["名称"]
        if "类型" in response.keys():
            ret["category"] = response["类型"]
        if "领域本体" in response.keys():
            ret["ontology"] = response["领域本体"]
        if "标准名" in response.keys():
            ret["officialName"] = response["标准名"]
        if "同义词" in response.keys():
            ret["synonyms"] = response["同义词"]
        if "解释" in response.keys():
            ret["description"] = response["解释"]
        return ret

    def parse_response(self, response: str, **kwargs):
        rsp = load_NER_data(response)
        # rsp = self.process_data(response)
        ret = []
        for r in rsp:
            if isinstance(r, list) and len(r):
                r = r[0]
            if not isinstance(r, dict):
                continue
            ret.append(
                self.process_en(r, **kwargs)
                if KAG_PROJECT_CONF.language == "en"
                else self.process_zh(r, **kwargs)
            )
        return ret
